### PR TITLE
Fix crash with protected_attributes and rails 4.2

### PR DESCRIPTION
**Pull request by brauliobo**

### CODE REVIEW

**Comment by sneakernets** [comment]
Thanks for figuring this out!

**Comment by pothoven** [comment]
Thanks for the fix!
Before I pull it in, I noticed you removed checks and alternative code for various Rails versions.  Will this work for all versions?

**Comment by pothoven** [comment]
There was already another proposed fix for this problem in this pull request (https://github.com/pothoven/attachment_fu/pull/13) that I hadn't seen until I saw yours.  Any thoughts on it compared to yours?

**Comment by brauliobo** [comment]
This PR uses the `send("#{attr}=", value)` which is agnotisc of where the `protected_attributes` is being used or not. This also simplified the code and made the version check not necessary anymore.

**Comment by pothoven** [comment]
I agree.  While I like that PR #13 was able to fix it with a 1 liner, I like that your fix also simplified the code.  I'll pull in your fix and make a new version of the gem.

**Comment by brauliobo** [comment]
thanks @pothoven, I'll remove the monkey patch in my code :)

**Pull request merged**
